        <div class="flex_box">
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_KE" value="KE"><label class="custom-control-label" for="air_KE"><img src="../images/airline/KE.png" class="air-icon">대한항공</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_OZ" value="OZ"><label class="custom-control-label" for="air_OZ"><img src="../images/airline/OZ.png" class="air-icon">아시아나</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_7C" value="7C"><label class="custom-control-label" for="air_7C"><img src="../images/airline/7C.png" class="air-icon">제주항공</label>
                </div>
            </div>							
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_LJ" value="LJ"><label class="custom-control-label" for="air_LJ"><img src="../images/airline/LJ.png" class="air-icon">진에어</label>
                </div>
            </div>							
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_TW" value="TW"><label class="custom-control-label" for="air_TW"><img src="../images/airline/TW.png" class="air-icon">티웨이</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_BX" value="BX"><label class="custom-control-label" for="air_BX"><img src="../images/airline/BX.png" class="air-icon">에어부산</label>
                </div>
            </div>							
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_RS" value="RS"><label class="custom-control-label" for="air_RS"><img src="../images/airline/RS.png" class="air-icon">에어서울</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_RF" value="RF"><label class="custom-control-label" for="air_RF"><img src="../images/airline/RF.png" class="air-icon">에어로케이</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_4H" value="4H"><label class="custom-control-label" for="air_4H"><img src="../images/airline/4H.png" class="air-icon">하이에어</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_4V" value="4V"><label class="custom-control-label" for="air_4V"><img src="../images/airline/4V.png" class="air-icon">플라이강원</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_ZE" value="ZE"><label class="custom-control-label" for="air_ZE"><img src="../images/airline/ZE.png" class="air-icon">이스타항공</label>
                </div>
            </div>
            <div class="group01">
                <div class="check-group custom-checkbox" onClick="return airCheck()">
                    <input class="custom-control-input" type="checkbox" checked name="airLine" id="air_WE" value="WE"><label class="custom-control-label" for="air_WE"><img src="../images/airline/WE.png" class="air-icon">파라타항공</label>
                </div>
            </div>
        </div>